### ISSUE TITLE
Events that are Enforced by Interfaces

### ISSUE THREAD

**Issue by ph0ph0** [onflow/cadence#1161]
### Issue To Be Solved

Currently, it is not possible for interface creators to ensure that contracts will emit events at predefined times if they employ a contract/resource interface and its functions. Given Flow’s resource-oriented model, events are critical for keeping track of resources within and across ecosystems. As standards become more prevalent and the applicability of interfaces grows, it will become increasingly important that developers are guided as to when events should be emitted. This will benefit infrastructure that exists above the contract level and could also allow for use-cases beyond those imagined by the contract creator. 

I believe that this is similar to, though not the same as this feature request here:

https://github.com/onflow/cadence/issues/1059

In the above feature request, bluesign is referring to default events for critical resource operations, which I don't interpret as enforced custom events, though there is clearly overlap. 

### Suggested Solution

One way that events might be enforced could be through postconditions in a function call described by an interface.

**Comment by bluesign** [comment]
@ph0ph0  This is a problem I thought a lot about on about. 

Putting enforcement in interface is a bit tricky. Problem is mostly need to check also the payload, so if you check eventType, and also if you check payload, question is why you don't yourself emit ( as interface ) this event.  That way also developer needs to thing about one less thing.

**Comment by ph0ph0** [comment]
That's true, I suppose the interface wouldn't have to enforce it, on the condition that you could somehow get the interface to handle the event emission itself. However, as far as I am aware, this is not possible as you can't add logic to functions in an interface (and therefore emit an event) and you can't emit events in pre/post conditions?

**Comment by dete** [comment]
This one has always bothered me, too. As Bluesign points out, it's actually MORE work to create a post-condition that checks that an event has been emitted than it is to actually emit the event! I've also always just told myself that "you can't check everything with post-conditions".

Here's a whacky idea: What if methods themselves were tagged as "traceable" instead of manually creating events?  _Whenever_ such a method were called, an event would be emitted with the Resource ID of the receiver, plus the name and argument list of the function.

So, instead of this:
```
pub event DepositEvent(amount: Int)

pub fun deposit(amount: Int) {
   // some logic
   emit DepositEvent(amount: amount)
}
```
You'd just have:
```
pub traceable fun deposit(amount: Int) {
   // some logic
}
```

In the rare case where you have a method that only _sometimes_ emits an event, you'd have to declare a stub traceable method that you call that doesn't otherwise do anything interesting, but that's no more boilerplate than defining and emitting a new event type...

The only real trick is that the event would need to have a good way of serializing Resource references or instances, but I think that's actually an ADVANTAGE...

**Comment by joshuahannan** [comment]
I actually like this a lot! Even if we could require that functions emit certain events, there is still the problem that we can't know for sure if the event fields are actually accurate values. This way, we could at least ensure that some of the values are accurate, because they were the actual arguments of the function! But having the option for both this and events would be really nice.

**Comment by turbolent** [comment]
This should be possible now by adding even emission in conditions
