### ISSUE TITLE
Properly handle user and implementation errors returned from atree

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1255]
### Problem

Cadence uses the atree library for some of its data structures (arrays, dictionaries, and composite values).

Currently, all errors returned by atree are considered implementation errors. However, this is not always the case. For example atree might use FVM to read data from storage, and FVM may return a user error. Such a user error should be propagated to Cadence as is and not be treated like an implementation error.

### Suggested solution

Audit uses of atree in Cadence and poperly handle / distinguish between user and implementation errors.

### Notes

- https://github.com/onflow/cadence/blob/81c63bfef73cd4874d05b6274dbd2402a0a0b788/runtime/interpreter/value.go#L9216

**Comment by turbolent** [comment]
- Maybe use shared error library between FVM, Cadence, and atree

**Comment by turbolent** [comment]
TODO: Follow up on outcome from meeting with @fxamacker @janezpodhostnik @tarakby

**Comment by turbolent** [comment]
Want to have separate library for error types and use it across atree, Cadence, FVM, etc.

**Comment by j1010001** [comment]
Not blocking the release (not a security issue) but a tech debt we want to address ASAP.

**Comment by j1010001** [comment]
Post Secure Cadence cleanup

**Comment by j1010001** [comment]
bumping up the priority as this has been causing some pain in misleading errors: https://dapperlabs.slack.com/archives/C03C40ZV82C/p1672956533133159

**Comment by turbolent** [comment]
- [ ] @fxamacker atree: Categorize errors into 
  - Fatal errors (e.g. integrity check failing)
  - External errors (e.g. Ledger calls, callbacks (e.g. iteration); needs Unwrap function), and
  - User errors (e.g. index out-of-bounds)
- [ ] @dsainati1 Cadence: Add `Unwrap` function to `ExternalError`, so FVM can unwrap

**Comment by janezpodhostnik** [comment]
This is the FVM code used to unwrap an `ExternalError` because it doesn't have an Unwrap method https://github.com/onflow/flow-go/blob/c92aafc/fvm/errors/errors.go#L105. This could be removed if `ExternalError` could be unwrapped.

This is an error report https://github.com/onflow/flow-go/issues/3729 of an instance where Cadence misinterprets an error and because of that adds the whole call stack to the error.

Here is the code of how the FVM differentiates an implementation error from a user error: https://github.com/onflow/flow-go/blob/c92aafc3b93c0668a5d5e7da048b08bdae174809/fvm/errors/errors.go#L70
It basically boils down to:
- if its a CodedError (FVM error) and if its code is a failure code then it is an implementation error, if not, unwrap it and check if inside is an implementation error
- if it is an unwrappable error check if it contains an implementation error
- if it is not unwrappable and not a CodedError, then it is an implementation error

**Comment by j1010001** [comment]
we need to update the atree version to the latest

**Comment by fxamacker** [comment]
PR #2426 uses latest atree and updates handling of user errors.

If additional integration is needed, please feel free to open separate PRs as that may require more knowledge of Cadence internals.

I can tag a new release of atree if we didn't miss anything and this works out.

cc: @j1010001 @turbolent

**Comment by fxamacker** [comment]
- [x] Tagged onflow/atree [v0.6.0](https://github.com/onflow/atree/releases/tag/v0.6.0).
- [x] Updated PR #2426 to use atree v0.6.0.
