### ISSUE TITLE
Investigate mutability improvements

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1260]
The issue we are trying to guard against here is how to make it more difficult for Cadence developers to accidentally shoot themselves in the foot by accidentally exposing a mutable variable to an external contract or transaction. Currently, Cadence prevents you from overwriting the value stored in a `var` outside of the scope where it was defined unless that `var` is given the `pub(set)` access modifier, allowing external code to write to it. However, this does not protect against mutative operations that modify these values, as in the following example:

```
pub contract Foo {
	pub let x : [Int]

	init() {
	    self.x = [3]
	}
}

pub fun bar() {
	Foo.x[0] = 1
}
```

This still mutates the value of `x`, but Cadence does not protect the developer against this. We would like to devise a solution to protect against this footgun.

**Comment by dsainati1** [comment]
I am currently investigating a possible improvement here that would only allow values like arrays and dictionaries to be mutated in the context in which they can be written, instead of the current behavior which allows them to be mutated in any context in which they can be read.

An demonstration of this is implemented in draft PR https://github.com/onflow/cadence/pull/1267. 

There are, however, some open questions about this solution:

1) How onerous would this change be for existing contracts and transactions? It is possible to resolve any type errors caused by this additional restriction by adding a setter to the field's enclosing structure, but how much of a burden will this place on developers to do?

2) What should the behavior be for `pub(set)` accessible variables? What about a publicly settable field nested in a constant? Consider the following code:

```
pub struct Bar {
    pub let foo: Foo
    init() { 
       self.foo = Foo()
    }
}

pub struct Foo {
    pub(set) var x : [Int]

    init() {
       self.x = [3]
    }
}

pub fun bar() {
    let bar = Bar()
    bar.foo.x[0] = 3 // should this be an error?
}
```

3) Are there any other values besides arrays and dictionaries that deserve this kind of mutation protection or are subject to the same footgun?

**Comment by turbolent** [comment]
Thank you for adding a good description @dsainati1 👍

**Comment by SupunS** [comment]
Are we only considering the mutability of contract fields (more precisely: storable fields)? Asking this because, when references come into play, things could get a little bit complex. Then a reference to a single value could be in two different object trees: one tree might be mutatable while the other might not.

**Comment by dsainati1** [comment]
This is an interesting case, and one that I am not sure how to solve. Any kind of analysis that would prevent this case would either have to be very complex and track pointers to references to see all the possible effects that each mutation would have, or it would have to simply ban assigning an immutable field with a reference type into a mutable one. Neither of these approaches feel particularly compelling to me.

On the other hand, it's possible that protecting against this case is not in scope for this issue. The goal here is to prevent people from accidentally exporting a mutable field from their contracts, and this would require users to explicitly declare a `pub(set) var` and assign an immutable field into it, which seems difficult to do by accident. 

Consider that users would still be allowed to create a `pub fun` that would mutate the value of a `pub let` field, which feels similar in that it could cause still cause problems, but is less likely to happen without the user's knowledge. 

Curious to hear @turbolent's thoughts on this.

**Comment by j1010001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Flow-Protocol-5a2ad022cee40e25b0885f82/issues/onflow/cadence/1260?planning-poker) with ZenHub @SupunS @robert-e-davidson3 @turbolent @dsainati1
