### ISSUE TITLE
Remove type requirements

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1283]
Scope:
Remove feature completely from the codebase.
Feature: Interface can require a concrete type to specify a nested type.
Code removal, updating test cases and docs.

Not in scope:
1) storage migration for FT/NFT contracts.
2) rewrite of FT/NFT token standards

Note: This is only need if the community agrees we need a token contract rewrite.

- [x] #2069 
- [x] #2081 

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/cadence/pull/2670
- [ ] https://github.com/onflow/cadence/pull/2662
```

**Comment by j1010001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Flow-Protocol-5a2ad022cee40e25b0885f82/issues/onflow/cadence/1283?planning-poker) with ZenHub @dsainati1 @robert-e-davidson3 @SupunS @turbolent

**Comment by j1010001** [comment]
Needs to be broken down.

**Comment by dsainati1** [comment]
As discussed in the last [LDM](https://github.com/onflow/cadence/blob/master/meetings/2022-11-02.md#removalreduction-of-nested-type-requirements), in order to do this we need to provide support for allowing interfaces to have events; as the new NFT/FT standards are going to feature interfaces with events. 

There are currently a few competing ideas for how this might be done:
    1) Keep type requirements for events, and limit them only to events
    2) Allow events to be emitted from interfaces directly
    3) Allow composites to inherit events from interfaces 

All of these have pros and cons worth considering. 

There is also a separate but related question of whether or how we want to enforce that events are emitted in certain cases. IMO this is not a prerequisite for solving this issue, but it is a related problem and our potential solution to that may inform our solution to this.
