### ISSUE TITLE
Crypto: Can't pass domainSeparationTag when using keyList.verify

### ISSUE THREAD

**Issue by gregsantos** [onflow/cadence#1305]
FCL is using `keyList.verify` via Cadence script in [`verifyUserSignatures()`](https://github.com/onflow/fcl-js/blob/master/packages/fcl/src/exec/verify.js).
It is used as part of [Provable Authentication](https://docs.onflow.org/fcl/reference/proving-authentication/) and for verifying arbitrary signed messages.

A wallet provider signs a message with a user's private key/s and returns the signature to FCL during authentication or as a separate service call.

### Signature Creation
The wallet prepends the default `domainSeparationTag` `"FLOW-V0.0-user"` to the `message`(hex string) before signing. 
An optional custom `domainSeparationTag` can be included by the app via `fcl.config()`

Here's how [`fcl.walletUtils` builds the message](https://github.com/onflow/fcl-js/blob/master/packages/fcl/src/wallet-utils/encode-provable-authn-signing.js) and the [signing function used by fcl-dev-wallet](https://github.com/onflow/fcl-dev-wallet/blob/main/src/crypto.ts):
```javascript
const message = USER_DOMAIN_TAG + (APP_DOMAIN_TAG ? 
        encode([APP_DOMAIN_TAG, 'FOO']).toString("hex")
        :
        encode(['FOO']).toString("hex")
```

Verifying a `signatureSet` with encoded message as described above returns true. An invalid signature returns false.

```javascript

let isValid = keyList.verify(
    signatureSet: signatureSet,
    signedData: message.decodeHex()
)

// `isValid` is true for valid signature
```

[Cadence Documentation](https://docs.onflow.org/cadence/language/crypto/#signature-verification) illustrates including `domainSeparationTag` as an argument to `publicKey.verify`.
```
let isValid = pk.verify(
    signature: signature,
    signedData: message,
    domainSeparationTag: "",
    hashAlgorithm: HashAlgorithm.SHA2_256
)
```

## Problem

- Attempting to pass `domainSeparationTag` as arg to `keyList.verify` ERRORS, expecting 2 args only.
- Verifying a message with a default `"FLOW-V0.0-user"` **+ custom domainSeparationTag** tag returns true (despite not including `domainSeparationTag`)

```javascript
const message = USER_DOMAIN_TAG + (APP_DOMAIN_TAG ? 
        encode([APP_DOMAIN_TAG, withPrefix(address), timestamp]).toString("hex")
        :
        encode([withPrefix(address), timestamp]).toString("hex")

// In Cadence Script
let isValid = keyList.verify(
    signatureSet: signatureSet,
    signedData: message.decodeHex()
)

// `isValid` is true for valid signature        
```

### Outcome

**I'm trying to determine the following:**

- If `keyList.verify` should accept the same args as `publicKey.verify` including `domainSeparationTag`
- If a custom `domainSeparationTag` can be passed to `keyList.verify` and checked against the `signatureSet`
- Why the current implementation returns `true` for message/signature that includes `"FLOW-V0.0-user"` + `CUSTOM_DOMAIN_TAG` despite passing no domainSeparationTag to `keyList.verify`

**Comment by turbolent** [comment]
The implementation of the Crypto API is split between Cadence and flow-go/FVM: Cadence contains the API, but the actual implementation (i.e. here, signature verification) is performed in flow-go/FVM.

As far as I understood the design of the API, a signature may only have one domain separation tag, but I am not sure.

@tarakby Could you please have a look here?

**Comment by tarakby** [comment]
- you are right, `KeyList` verify function does not accept a tag as specified in Cadence doc : https://docs.onflow.org/cadence/language/crypto/#key-lists
```
pub fun verify(
        signatureSet: [KeyListSignature],
        signedData: [UInt8]
    ): Bool
```
The historical reason is that `KeyList` was introduced long time before we added support for tags or non-ECDSA algorithms, and didn't get updated afterwards. 

- The `KeyList` methods are implemented by a [contract](https://github.com/onflow/cadence/blob/master/runtime/stdlib/contracts/crypto.cdc) , and it is re-using the same `PublicKey.verify` function, with the tag set to the ECDSA [user tag](https://github.com/onflow/cadence/blob/master/runtime/stdlib/contracts/crypto.cdc#L126-L130).

- If you are using ECDSA, you can notice that verifications on-chain only accept one specific user tag, as specified by the doc:
```
domainSeparationTag is the domain tag used for signing. The interface only accepts the user tag "FLOW-V0.0-user".
```
The tag parameter was introduced to serve BLS tags while keeping the same `PublicKey.verify()` API for all signature algos. If we were to support ECDSA only, we could omit the tag from the API and just force all verifications to use the hardcoded "FLOW-V0.0-user". 

- Back to the tests @gregsantos made with the verification being successful. I'm wondering if the message passed to `keyList.verify` doesn't include `USER_DOMAIN_TAG`, since it's already added by the contract?

**Comment by gregsantos** [comment]
Thanks for clarifying things @turbolent @tarakby !
Closing, as things are working as expected using `keyList.verify`
