### ISSUE TITLE
Cadence Error in testnet

### ISSUE THREAD

**Issue by KSlashh** [onflow/cadence#1781]
### Error
 [Error Code: 1101] cadence runtime error Execution failed:
error: runtime error: invalid memory address or nil pointer dereference

### Transaction
https://testnet.flowscan.org/transaction/7d98e36a67133618a706049b5e5e64de10ec8af5b9f71e1a3dd5a3f7ddf8b7d1

### Description
These functions work fine around a month ago. Emulator won't throw any error.  Addtional tests show that it works fine before A.203ea2804f661311.LockProxy: 212 (tx is supposed to end in line 216), so I think maybe it is not a contract error. Actually, it looks from golang.

**Comment by SupunS** [comment]
Hi @KSlashh, It seems like in the pre-condition of `receiveCrossChainMessage` of the `MessageReceiver` interface, the `crossChainMessage` is destroyed after sending to `checkCrossChainMessage`. 
And then in the method implementation, LockProxy: L#90, the same resource is destroyed once again. Using/destroying an already destroyed resource is not valid. You may have to re-visit the logic of the contract to properly handle it.

There was also a bug in the Cadence code where it was throwing a nil-pointer instead of giving a proper error message. I've fixed it with https://github.com/onflow/cadence/pull/1783.

**Comment by KSlashh** [comment]
Thank you for the detailed reply @SupunS. But I think this error is not caused by `Using/destroying an already destroyed resource`. Please check [this transaction](https://testnet.flowscan.org/transaction/c0d387d92db0ee957e14cbcc920ce4eda94add6578e5dadf7202a7564b1a630f/script), it works fine until LockProxy: L#210, it is way after the double-destroy codes. So maybe something else caused that?

Double-destroy may also be an unfixed error, I've pull an issue [#1784 ](https://github.com/onflow/cadence/issues/1784) on it.

**Comment by SupunS** [comment]
[That second transaction](https://testnet.flowscan.org/transaction/c0d387d92db0ee957e14cbcc920ce4eda94add6578e5dadf7202a7564b1a630f) is failing at the `unlock(...)` function which is called prior to the destroy statement in `receiveCrossChainMessage(...)`.
