### ISSUE TITLE
Emulator crash

### ISSUE THREAD

**Issue by kharlov-art** [onflow/cadence#196]
### Problem

Emulator is crashing

### Steps to Reproduce

0. use emulator in vs code
1. use any contract that creates resources, for instance FungibleToken from playground
2. create a resource and a public link, `acct.link<&FungibleToken.Vault{FungibleToken.Receiver, FungibleToken.Balance}>(/public/MainReceiver, target: /storage/MainVault)`
3. execute script that returns a reference 
```
pub fun main(): &FungibleToken.Vault{FungibleToken.Balance} {
    let acct1 = getAccount(0x01cf0e2f2f715450)
    let acct1ReceiverRef = acct1.getCapability(/public/MainReceiver)!
                          .borrow<&FungibleToken.Vault{FungibleToken.Balance}>()!
    return acct1ReceiverRef
```
4. see thrown exception `panic: cannot convert value of type *interpreter.StorageReferenceValue`
5. no other transaction/script can be executed after that

### Acceptance Criteria

Such scripts shouldn't crash the emulator at run-time, but rather have to report an error.

**Comment by turbolent** [comment]
Thanks for the bug report @kharlov-art!

Returning references from scripts is and won't be supported, because there is no way to serialize them, there is no way to use them off-chain, and it won't be possible to pass them to on-chain code, because that would allow forging references to potentially privately stored data.

This is a known issue: I've created #186 to improve this by statically rejecting functions with a return type that is not serializable, and also handling this at run-time more gracefully by not crashing and reporting a better error message.

**Comment by kharlov-art** [comment]
@turbolent sure, make sense, didn't expect to have a real reference returned, just tried it :)
In this case should we close this issue?

**Comment by turbolent** [comment]
Yep, closing in favour of #186
