### ISSUE TITLE
Flow built-in event IDs include "S" prefix

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#198]
### Problem

The following event IDs are now emitted with a `"S"` prefix, which introduces a breaking change for downstream Flow SDKs.

- `S.flow.AccountCreated`
- `S.flow.AccountKeyAdded`
- `S.flow.AccountKeyRemoved`
- `S.flow.AccountCodeUpdated`

https://github.com/onflow/cadence/blob/master/runtime/stdlib/flow_builtin.go#L224-L246

Currently the VM uses the type ID produced by Cadence to index events, and users can query for events using these IDs. It may be the case that the VM should sanitize these IDs, rather than using the exact ID that Cadence produces.

**Comment by turbolent** [comment]
The `S` prefix is now added because the events use a string location (`ast.StringLocation`).

The prefix is used to convert a location ID (just a string) to a `Location`, specifically from a type ID, in `ast.LocationFromTypeID`. This function is only used in `importCompositeValue`, i.e. the function to convert `cadence.Value`s to `interpreter.Value`. 

I'm not quite sure what the best way is to keep this backwards-compatibility while also keeping the current functionality without somehow special-casing the builtin Flow types.
