### ISSUE TITLE
Confusion about nested optionals

### ISSUE THREAD

**Issue by jamietdavidson** [onflow/cadence#2008]
- What version of Cadence are you using? Version: v0.39.3
- What operating system are you using? Mac OS X Monterey 12.3.1
- Are you having a problem with the language server in Visual Studio Code?
Yes

Is this a valid type? I am failing to understand how this is possible. Please help me understand what I am missing. I would post the contract to reproduce but it's still under active development and I need to keep it under wraps for the time being.

<img width="348" alt="Screen Shot 2022-09-26 at 6 32 07 PM" src="https://user-images.githubusercontent.com/80986926/192410836-a5dbf33e-2fb2-4256-8103-5d988731087b.png">

**Comment by jamietdavidson** [comment]
Also receiving:

```
Transaction ID: 83566d4d0d44d92ab7899fa10fbd8b17d6515d19a286eaf9e7686135b74d524d
❌ Failed to deploy contract
❌ Command Error: execution error code 1101: [Error Code: 1101] cadence runtime error Execution failed:
error: cannot deploy invalid contract
 --> 83566d4d0d44d92ab7899fa10fbd8b17d6515d19a286eaf9e7686135b74d524d:4:3
  |
4 |                     signer.contracts.add(name: name, code: code.decodeHex() )
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: mismatched types
   --> f8d6e0586b0a20c7.Graph:181:44
    |
181 |                 let relatedNodeId: UInt64 = self.edges[key]!
    |                                             ^^^^^^^^^^^^^^^ expected `UInt64?`, got `UInt64??`
```

When trying to deploy

**Comment by turbolent** [comment]
`UInt64??` is indeed a valid type: Cadence's optionals are based on the [Option type](https://en.wikipedia.org/wiki/Option_type). Optionals can be arbitrarily nested, e.g. `UInt64????` is also a valid type. Think of it like a box that can be empty or contain a value. You can nest boxes, so so you can nest optionals. Usually you only need and want one level. A good intuition is another container type: arrays can contain zero or more elements, and it can be nested, so e.g. a type like `[[UInt64]]` is valid.

Let's also shortly talk about dictionaries. Indexing into a dictionary, i.e looking up a certain element, results in an optional – the dictionary may contain the key, or it may not. So for example, looking up a key in a dictionary with type `{String: UInt64}`, results in an optional, `UInt64?`.

Now to your code. In your case, `edges` likely has already an optional value type, e.g. `{String: UInt64?}`. Again, the result of a lookup is an optional, so you get a `UInt64??`. There is no need to make the value type optional, so I'd recommend simplifying it to just `UInt64`.

Next, you are performing the lookup `self.edges[key]!`, which force unwraps the result of the lookup, `UInt64??`, which results in `UInt64?`. However, you are also declaring that the result should be `UInt64` (`let relatedNodeId: UInt64 = `), which it isn't. The confusing error will go away once you properly matched the types: Either remove the wrong type annotation from the variable declaration and just have the type inferred (`let relatedNodeId =`), or correct it to the type that is actually returned `self.edges[key]!` returns `UInt64?`, not a `UInt64`.

Again, the root cause of the confusion likely stems from using an optional value type in the dictionary and then dealing with nested optionals because of it. Simplifying the dictionary type will also simplify working with the dictionary.

**Comment by jamietdavidson** [comment]
Hi @turbolent !

Thanks for the explanation. I didn't realize that `self.edges[key]` would return `nil` if nothing was found. I was. under the assumption that an exception would be thrown. That makes total sense! Thank you for the explanation, it is much appreciated :0.

**Comment by bluesign** [comment]
@turbolent This is one of the areas I cannot grasp ( though I have a theory ) is there a single use case for `UInt64??` ?
