### ISSUE TITLE
Enums defined in a contract interface are unusable when imported

### ISSUE THREAD

**Issue by NtTestAlert** [onflow/cadence#2116]
Tested on newest emulator

### Problem

Enums defined in a contract interface are unusable in implementing contract

### Steps to Reproduce

```cadence
// Iface.cdc
pub contract interface Iface {
 pub enum TestEnum: UInt8 {
   pub case Initialized
   pub case Other
 }
 // error: enum interfaces are not supported
 //pub enum interface TestEnumI {
 //   pub case Initialized
 //   pub case Other
 //}
}
```

// TestContract.cdc
```cadence
import Iface from "./Iface.cdc"
pub contract TestContract {
    pub enum TestEnum: UInt8 {
        pub case Initialized
        pub case Other
    }
    pub var canUseType:Iface.TestEnum?
    //                 ^^^^^^^^^^^^^^ works properly
    pub fun crashes() {
        self.canUseType = Iface.TestEnum.Initialized
        // ERROR          ^^^^^ not found in this scope
        //    cannot find variable in this scope: `Iface`
    }
    pub fun alsoCrashes(): Bool {
        return self.canUseType! == Iface.TestEnum.Initialized
        // ERROR                   ^^^^^ not found in this scope
        //    cannot find variable in this scope: `Iface`
    }
    pub fun alsoCrashes2(): Bool {
        return self.canUseType! == TestEnum.Initialized
        // ERROR error: cannot apply binary operation == to types: `Iface.TestEnum`, `TestContract.TestEnum`
    }

    init() {
        self.canUseType = nil
        // works
    }
}

```

**Comment by SupunS** [comment]
Nested types (structs, resources, enums) defined in interfaces are only "type requirements", but not concrete type definitions: (see: https://developers.flow.com/cadence/language/interfaces#nested-type-requirements).

i.e: They only mandate the interface implementations to also implement the type. Moreover, since they are not concrete type definitions: they cannot be used to create a value or used as a value (enum cases are values). 

This can be somewhat confusing. Because of the same reason, there is a proposal to remove this "type requirement" feature: https://github.com/onflow/cadence/issues/1283.

**Comment by turbolent** [comment]
This works as expected, so closing. 

@NtTestAlert let us know if you have any questions regarding this!

**Comment by SupunS** [comment]
Type requirements are enforced only if a contract conforms to a contract interface.
i.e:
```cadence
pub contract TestContract:  Iface {
   ...
}
```

**Comment by SupunS** [comment]
Once you add the conformance like above, the enum `TestContract.TestEnum` would implicitly conforms to the enum `Iface.TestEnum`.

Then you can do the assignment like:
```cadence
pub fun test() {
        self.canUseType = TestEnum.Initialized
}
```

Note that, if you want to compare, then you'll first need to downcast it to the intended type:
```cadence
return (self.canUseType! as! TestEnum) == TestEnum.Initialized
```

**Comment by NtTestAlert** [comment]
Ok, thank you :)
