### ISSUE TITLE
Inconsistent representation of byte arrays

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#212]
### Problem

The newly added `toBytes` and `toBigEndianBytes` methods return byte arrays typed as `[UInt8]`, whereas the `Crypto` contract accepts public keys, signatures and messages typed as `[Int]`. To support compatibility between these APIs, the types should be consistent.

`[UInt8]` is more correct -- is there any reason not to update all existing byte array representations to be typed this way?

**Comment by turbolent** [comment]
The use of `[Int]` for "byte arrays" has two reasons: historical and type inference.

As far as I remember, when we introduced the first APIs, there was only `Int`. We do have `UInt8` now, so should update the existing functions which accept and return `[Int]`, but actually are byte arrays. This is little work and probably not too big of a breaking change.

The bigger problem is type inference: The functions with "byte array" parameters are usually invoked with literals (e.g. `[1, 2]`), which are inferred to `[Int]`, so not compatible with `[UInt8]`. So *just* changing the parameter types would break existing code, because even though the literals are probably correct (the integer literals are in the `UInt8` range), the type is now incorrect. 

One option is to break existing code (probably e.g. transactions deploying code, adding keys, etc.):
Array literals like above will no longer work and developers have to pass correct `[UInt8]` values.
This would basically mean replacing the array literals with `String.decodeHex` calls. There's nothing to be done on the Cadence side for this option, only for developers.

Another option is to improve type inference. This is significant work, as we have to figure out how to improve the local type inference to be non-local, e.g. by proposing types while checking (a parameter type would be used as the proposed type when checking an argument type).

**Comment by psiemens** [comment]
Seeing as most clients use the pre-defined account creation templates, and given that we now have support for transaction arguments, I think it would be okay to introduce a breaking change and then provide new transaction templates that are compatible.

**Comment by turbolent** [comment]
Sounds good! OK if I then update all APIs which have `[Int]` parameters or return types, but semantically should be byte arrays, to `[UInt8]`?

**Comment by psiemens** [comment]
Yep, that sounds perfect!
