### ISSUE TITLE
Add examples to testing framework docs

### ISSUE THREAD

**Issue by MrDSGC** [onflow/cadence#2236]
### Issue to be solved

Cadence Testing Framework documentation could use some examples to help users test on Flow

https://discord.com/channels/613813861610684416/1055155961196728380/1055155961196728380

### Suggested Solution

Add examples to Cadence Testing Framework

**Comment by j1010001** [comment]
can we get some help from core-contract team here @franklywatson ?

**Comment by franklywatson** [comment]
Been chatting to the SCE team and we still feel that it's some ways away from widespread use. @satyamakgec made a valiant effort to code as much of the testing in [Offers](https://github.com/onflow/Offers/tree/offers-implementation/lib/cadence/test) using the framework over the past weeks. The TL;DR still remains, it's not there yet. Until then it doesn't make sense to cut examples (though the above repo already give us the base material for when it's needed)

1. [Allow defining types or contracts locally in the test file itself](https://github.com/onflow/cadence/issues/2075) - my understanding is that this is one of the more frustrating things
2. [Contracts, scripts and transactions as first-class citizens in testing framework](https://github.com/onflow/cadence/issues/1993) Somewhat duplicates #1 but looking at different aspects 
3. [Provide detailed information about the error during smart contract execution in test](https://github.com/onflow/cadence/issues/2076) This is required to cover negative test cases of the contract so that all code branches get coverage
4. No GH issue - right now it is impossible to return & consume a variable return type from the scripts within the testing framework, but there should be something so that these can be properly tested

**Comment by SupunS** [comment]
> No GH issue - right now it is impossible to return & consume a variable return type from the scripts within the testing framework, but there should be something so that these can be properly tested

I think this is https://github.com/onflow/cadence-tools/issues/33. This is fixed in the latest CLI.

**Comment by m-Peter** [comment]
As part of an ongoing grant proposal, regarding code coverage, I have setup this [repository](https://github.com/Build-Squad/flow-code-coverage) which I intend to use for the adoption milestone, and as a learning resource for the Cadence testing framework.
I would like to undertake this issue, if you also agree, and enrich the following [doc](https://developers.flow.com/cadence/testing-framework). I have a lot of examples, scattered in [gists](https://gist.github.com/m-Peter/c16d6f0ead4a6b3495635a479626b672#file-test_test_contract-cdc). cc @SupunS @turbolent

**Comment by SupunS** [comment]
Sounds good!

Closing this issue since examples have been added to the docs as mentioned above. Please feel free to re-open or open a new issue if you feel there are more areas we can improve on the docs.
