### ISSUE TITLE
Extend ordering comparisons (< , <=, etc) to support container types

### ISSUE THREAD

**Issue by dreamsmasher** [onflow/cadence#2276]
### Issue to be solved

Currently, we only support ordering comparisons for numeric types. This could be extended to other built-in types like strings, booleans, and containers whose inner types are comparable. This is particularly useful for common operations like sorting arrays of strings, binary search, and implementing dynamic lookup tables.

### Suggested Solution

While equality for values is defined by the `Equatable` interface in the interpreter, The comparison operators `Less`, `LessEqual`, `Greater`, and `GreaterEqual` are defined as part of the [`NumberValue` interface](https://github.com/onflow/cadence/blob/0354a413c16f3844b6f0bff42292a00f3121ab62/runtime/interpreter/value.go#L2691). Opening up more Cadence types for comparison would require these ops to be factored out into a new interface, `Orderable`, from which `NumberValue` can inherit.

As part of an MVP, ordering should be defined for the following types:
- `Bool`: `false < true`
- `[T]` if T is orderable: lexicographic ordering, e.g. `[1, 2] < [1, 2, 3]`, `[1] < [2]`
- `[T; N]` if T is orderable: lexicographic ordering. Both the left and right-hand expressions in the comparison must have the same lengths, otherwise they're different types.
- `String`: lexicographic ordering according to grapheme values, e.g. `"OwO" < "UwU"`, `"😎" < "🥺"`
- `T?` if T is orderable: lexicographic ordering. Let the expression `Some(x: T)` denote that `x` is not `nil`:
  - `nil == nil`
  - `nil < Some(x)`
  - `Some(x) < Some(y)` = `x < y`

Documentation and tests should be updated accordingly to reflect the new behaviour.

## Open questions
- Should `Void` support comparisons?
  - We already allow `() == ()`, which is true.
  - Allowing the other comparison ops, while not particularly useful, would be logically consistent with the other changes this issue proposes.

- Should comparing `Optional`s be polymorphic?
  - Equality comparisons for `Optional` values of different nesting levels are already allowed as long as the base type is the same, e.g. 
  - ```cadence
      let x: Int?? = 1
      let y: Int? = 1
      let z: Int = 1
      x == y // true
      x == z // true

      let w: Int????????? = nil
      w == x // false
    ```
  - This is consistent with the behaviour of `Optional` values in Swift.
  - However, Swift doesn't allow for optionals to be ordered.
  - I argue that we should diverge from Swift and allow for ordering in this case. In a comparison, nested optionals should be flattened down to a single level, and non-optionals should be treated as non-nil. Comparison can then proceed according to the above rules.

**Comment by darkdrag00nv2** [comment]
Hi @turbolent, if this is up for grabs, I am willing to take a stab at this.

**Comment by turbolent** [comment]
Yeah, this issue is definitely up for grabs.

Before starting on implementing the suggestion, we should first discuss the proposed additions a bit. 

- Cadence draws a lot of inspiration from Swift and Kotlin. In both languages the protocol/interface is called `Comparable`, see https://developer.apple.com/documentation/swift/comparable and https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-comparable/. We might want to follow that naming
- In Swift, `Bool` is not comparable. In Kotlin, it is. I guess it could be useful to add it
- Neither in Swift nor in Kotlin are arrays comparable
- In both Swift and Kotlin, `String` and `Character` are comparable. This should be pretty useful
- Swift used to support comparisons for optionals, but *removed* support. The proposal for the change has a great explanation why. We should probably hold off with that

I guess adding support for comparing `Bool`, `String`, and `Character` is pretty non-controversial / a good start, and we can maybe continue discussing the others.

**Comment by darkdrag00nv2** [comment]
@turbolent Do we want to add support for any other container?

Personally, I don't think we should add comparison for arrays or optional. I think `String` should be the last one we should support #2470

**Comment by turbolent** [comment]
@darkdrag00nv2  Agreed, I think we can close once #2470 is in

**Comment by turbolent** [comment]
Thank you @darkdrag00nv2 for taking this on 👏
