### ISSUE TITLE
Language support to create Address from [UInt8] byte array

### ISSUE THREAD

**Issue by gunnark-ab** [onflow/cadence#2433]
### Issue to be solved

Support for initializing addresses from `[UInt8]`

### Background

The `Address` type has a `toBytes()` method, but doesn't support creating an `Address` from a `[UInt8]`.

### Suggested Solution

Add a `Address` constructor which accepts `[UInt8]`:

```cadence
let bytes = [50, ... 54]
let addrFromBytes:Address = Address(bytes) // panic if constructor argument is not convertible into a valid address
```

**Comment by turbolent** [comment]
Modified the title and description to focus on just the creation from `[UInt8]`, as the creation from a `String` is already covered in #2154

**Comment by darkdrag00nv2** [comment]
@turbolent FYI - I'll take a shot at this

**Comment by turbolent** [comment]
@darkdrag00nv2 sounds good! Let me know if you have any questions

**Comment by darkdrag00nv2** [comment]
@turbolent Yes, did some digging in the codebase. Looks like we need to declare a new conversion function for this?

There is [already a conversion function](https://github.com/onflow/cadence/blob/147e51edb14ae515b6d59ef9fe75de410d0e61b6/runtime/interpreter/interpreter.go#L2674-L2680) which accepts an `IntegerType`. Not sure if there is a way to accept either [uint8] or an `IntegerType`.

**Comment by turbolent** [comment]
Correct, there is already a [built-in conversion function `fun Address(_ integer: Integer): Address`](https://github.com/onflow/cadence/blob/147e51edb14ae515b6d59ef9fe75de410d0e61b6/runtime/sema/type.go#L3314).

Given that Cadence does not support function overloading, we use a pattern similar to what Deniz mentioned above, having a function named `TargetType.fromSourceType`, e.g. here `Address.fromBytes`. 

For example, we already have such functions for `String`: `String.fromUTF8` and `String.fromCharacters`.
If you look at how those functions are defined in `sema` and `interpreter`, you should be able to do pretty much the same for `Address.fromBytes`.

Later we could have such a `fromBytes` function for all `Number` types, as we already have a "to bytes" function.

Which brings up a good point: A number represented as a "byte array" might be in either one of two representations: little-endian or big-endian. Developers/users might assume either one representation as "normal". For this reason we named the "to bytes" functions explicitly `toBigEndianBytes`.
Maybe we should do the same for the "from bytes" functions, i.e. name the new function `fromBigEndianBytes`?

This would align with Cadence's general design principle of being a little more verbose if it can prevent bugs that might be caused by implicit behaviour or assumptions.
