### ISSUE TITLE
Add `fromBigEndianBytes` conversion function to `Number` types

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2448]
## Issue to be solved

To convert a number to a byte array, `Number` types have a function `toBigEndianBytes`.

The inverse function to convert a byte array to a number is missing.

## Suggested Solution

Add `fromBigEndianBytes` functions to all `Number` types.

**Comment by darkdrag00nv2** [comment]
@turbolent Quick question regarding the behavior on invalid inputs.

What do we want to do in case of underflow/overflow input?

```cadence
// Size of the byte array is more than 2.
let a = UInt16.fromBigEndianBytes([1, 2, 3, 4, ....])

// size of the byte array is less than 2.
let b  = UInt16.fromBigEndianBytes([1])
```

I would assume that for both the cases we would want to return `nil` but good to know your thoughts.

**Comment by darkdrag00nv2** [comment]
>In the case of to many bytes given / overflow, we can panic like you mentioned in the edit.

Hmm, based on the review comments on the implementation of `Address.fromString`, shall we return Nil in this case?
cc: @dsainati1 

>Int the case of too few bytes given, we can just "prefix pad with zeros"

Similarly, shall we consider only allowing `[0, 0, 0, 1]` instead of prefix padding `[1]`? Same logic as what padding with `0x` in `Address.fromString`. Personally, I feel we should do the padding i.e. allow `[1]` as well but just wanted to raise the point.

**Comment by darkdrag00nv2** [comment]
> Does Address.fromString require fixed-size input, or does it support shorter inputs (e.g. 0x1)?

Yes, `0x1` is valid for `Address.fromString`.

Makes sense, we will do the padding for smaller sized inputs & return Nil on invalid input (overflow etc).
