### ISSUE TITLE
Restrict `capabilities.publish` to account's own capabilities.

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#2768]
### Issue to be solved

Currently it is possible to republish someone else's capability via new capabilities API, I think it makes sense to keep old restriction.

There are a lot of scenarios ( voting, gating with existence of NFT ) usually checking if account owns some balance or resource, by checking a public path capability. Now it will be extra burden for developers and small foot gun with this change of behaviour. 

### Suggested Solution

Only allow capabilities from same account address to published via `Account capabilities.publish`

**Comment by turbolent** [comment]
Related discussion in the FLIP: https://github.com/onflow/flow/pull/798#issuecomment-1505303836

**Comment by dete** [comment]
Can you be more specific about an example where this would break? And is this a situation where it's worth remapping people's assumptions rather than limiting utility? Because, if I'm reading your message correctly, you're not worried that someone will publish a Capability that they shouldn't, but that someone will see a published Capability and make inferences that aren't correct. (Like, I check the public "Balance" capability on your account and assume you have that much money, but actually you've just republished Bill Gates' Balance capability....)

**Comment by bluesign** [comment]
Yeah exactly, the problem is people’s assumptions actually. Actually I am having hard time finding a strong case for utility too. Considering it is public, entitlements requiring actions are off the table.

**Comment by turbolent** [comment]
@bluesign Would you be able to open a FLIP for this? It can be a very simple one, the proposed changes are minimal and are essentially just keeping the behaviour of the current (linking-based) capability API.
It could also just be a draft, and the team could assist in completing it.

**Comment by turbolent** [comment]
Draft implementation: #2782
