### ISSUE TITLE
Define what a "Primitive Type" is in Cadence

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#2929]
### Issue to be solved

Some logic (like in https://github.com/onflow/cadence/pull/2928) relies on a soft definition of certain types (e.g. string, int, bool) in Cadence being "primitive", as opposed to a complex type like an array, dictionary or composite. We should concretize this by specifying exactly which types are primitive vs concrete.

**Comment by j1010001** [comment]
@darkdrag00nv2 this is probably required for #2803

**Comment by darkdrag00nv2** [comment]
@j1010001 yeah, wondering if we need to limit the function on just primitive/containers of primitives though. Asked on the PR: https://github.com/onflow/cadence/pull/2945#issuecomment-1816985718

**Comment by darkdrag00nv2** [comment]
@turbolent @SupunS Any idea on how we want to approach defining a "Primitive" in Cadence? Like should this be a type, may be a subtype of `AnyStruct` or could it just be a constant array of types that we define without exposing to end users?

**Comment by SupunS** [comment]
I guess the requirement here is mostly for the implementation of the types, correct? i.e: an implementation detail rather than a user-facing separation of types. In that case, a simple function on `sema.Type` interface should be sufficient.

Having said that, what is the separation that is being required here? is it just container (arrays, dictionaries, composite) types vs non-container types? In the stable-cadence branch, I've introduced the same functionality by means of of function `ContainFieldsOrElements` on the `sema.Type`: https://github.com/onflow/cadence/blob/787812ff371458a49ff29f02aad66e20db938f30/runtime/sema/type.go#L142-L161

The original purpose of that method was to determine if a reference should be returned during member access, but if the 'technical' requirement is the same, then we can re-purpose/re-name it to something more generic

**Comment by SupunS** [comment]
The PRs/Issues linked (#2928 and #2803) are against the stable-cadence branch, so using the existing `ContainFieldsOrElements` method should be possible even now.

**Comment by SupunS** [comment]
I think in our documentation we never define or use the term 'primitive type' (the member access semantics use the term 'container type' vs 'non-container-type'). If we are going to use that technical grouping in multiple features, maybe it's a good idea to formalize/standardize this grouping (so the terminology is consistent across features/documentation) and also add it to the documentation as well.

**Comment by darkdrag00nv2** [comment]
> Having said that, what is the separation that is being required here? is it just container (arrays, dictionaries, composite) types vs non-container types?

@SupunS Yes, for the dereference feature, container vs non-container should be sufficient.

**Comment by darkdrag00nv2** [comment]
Actually, there are two slightly different requirements.

https://github.com/onflow/cadence/pull/2928 - primitives (int, bool, string) VS complex (array, dictionary, composite)
https://github.com/onflow/cadence/issues/2803 - primitives + containers of primitives VS other complex types

So I guess we could define primitives as int, bool, string etc. and then #2803 will have to also include containers of primitives separately.

**Comment by dsainati1** [comment]
Note that primitive types should also include `Address` and `Path` values (which function like numbers and strings, respectively)

**Comment by turbolent** [comment]
@dsainati1 It should be possible now to update https://github.com/onflow/cadence/pull/2928/files#diff-c34bee2125d8f3673160cc7b3c912540ad811b4622a66c3a2ed6c25fc94e1cb0R2091 based on https://github.com/onflow/cadence/pull/2975

**Comment by dsainati1** [comment]
https://github.com/onflow/cadence/pull/2980
