### ISSUE TITLE
Analyze usage of restricted keywords in composite fields on Mainnet

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#2998]
As @bjartek pointed out, some resources might be using field names that will be restricted keywords in Cadence 1.0.
We need to analyze contracts deployed on Miannet to identify those instances so that we can with with the developer to migrate the on-chain data for those cases, if any exist.

**Comment by bjartek** [comment]
Do we have a list of restricted keywords somewhere and where they cannot be present?

**Comment by bjartek** [comment]
[reserved-report.json](https://github.com/onflow/cadence/files/13873730/reserved-report.json)

i did a sql query with all instances of 
\slet <keyword>\s or \svar <keyowrd>\s for all the keywords in that file. 

uploaded the results as json here. Note that some of these only use it in temp variables but the list is 252 long so it is a lot better then starting looking at 3500 contracts.

**Comment by bjartek** [comment]
This query was run against mainnet on current block height when i run it.

**Comment by turbolent** [comment]
Thank you Bjarte!

I'll write an analyzer for the linter to only find fields

**Comment by turbolent** [comment]
I used #3022 to query all MN contracts from 2023-11-16 with the hard keywords of #3019, and results are:
- `event`: 4
- `contract`: 9
- `default`: 1

That means there are currently some contracts which are effected, but given there are thousands of contracts, the results are pretty OK, and we can also do something about it.

We already define some keywords to be soft keywords instead of hard keywords, i.e. they may be used as identifiers: https://github.com/onflow/cadence/pull/3019/files#diff-d4f2e1652a85c54fe0afb9d6c1ae50164d96d7051160e201669e9d6699e5bc2eR169. It seems reasonable to extend this list.

We could also consider allowing more keywords specifically for field identifiers. For example, while a declaration `event event()` seems odd and should be rejected, a field declaration `let event: T` seems reasonable.

**Comment by turbolent** [comment]
@SupunS @dsainati1 Could one of you maybe take this over and make the changes needed? It would allow me to help Faye with the atree inlining work

**Comment by SupunS** [comment]
I can have a look

**Comment by SupunS** [comment]
So apparently, hard keywords are restricted only in certain places (i.e: places where ambiguity can be created, such as composite declaration names, function names, etc.). And they are not restricted for fields, and many other places.
So these use-cases actually work even now. Added a test: https://github.com/onflow/cadence/pull/3057

**Comment by SupunS** [comment]
That was a bit of a surprise, I was under the impression that hard keywords are rejected everywhere, while soft keywords are allowed on certain places.
But realized it is slightly different from what I was assuming: hard keywords are allowed in certain places, while soft keywords are allowed everywhere.

**Comment by turbolent** [comment]
That's actually great to see! Could you also please add a comment to the code defining the hard and soft keywords explaining this?
