### ISSUE TITLE
Creating reference to type-erased reference errors at run-time

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3011]
### Current Behavior

With the new external mutability feature and the change to disallow references to references, it is still possible to access a nested reference externally.

This doesn't seem t be handled properly. 

The following two programs illustrate the problem for both member (field) access and indexing access:

```cadence
resource R {}

struct Container {
    let value: AnyStruct

    init(value: AnyStruct) {
        self.value = value
    }
}

fun test() {
    let r <- create R()
    let containerRef = &Container(value: &r as &R) as &Container
    let ref: &AnyStruct = containerRef.value  // <--- run-time error here
    destroy r
}
```

```cadence
resource R {}

fun test() {
    let r <- create R()
    let arrayRef = &[&r as &R] as &[AnyStruct]
    let ref: &AnyStruct = arrayRef[0]  // <--- run-time error here
    destroy r
}
```

Both programs result in the interpreter error:

```
error: invalid transfer of value: expected `&AnyStruct`, got `&R`
```

### Expected Behavior

Unknown

### Steps To Reproduce

See current behavior

### Environment

```markdown
- Cadence version: 1.0 / master
```

**Comment by turbolent** [comment]
@SupunS Could you maybe have a look at this?

**Comment by turbolent** [comment]
After some more tinkering I realized that this was not due to index vs member, but seems to be in general a problem. 

Reworked the title and description.

Could this maybe be caused by the accessed value having a static non-reference type (`AnyStruct`), but the underlying dynamic type is a reference value?

**Comment by SupunS** [comment]
There are a few tests for that exact scenario, and that seems to work: https://github.com/onflow/cadence/blob/24f277e481b23b683a11f75d487d685517c66c2f/runtime/tests/interpreter/member_test.go#L861-L881
Strange why this one fails 🤔

**Comment by turbolent** [comment]
It seems like the test is not catching the problem, because just like thereference, the referenced is also value-kinded. In the test cases of the description the referenced values are resources.

**Comment by dsainati1** [comment]
It seems like the error that is being reported is "correct" in the sense that the type at runtime is not compatible with the static type of the `ref` variable. We have no way to prevent this statically because of the `AnyStruct` upcast, so we are forced to prevent this at runtime. 

This is really unfortunate imo, because as far as I can tell we really only have one solution: adding a runtime "type mismatch" error for when a runtime type enters a variable whose static type is incompatible with that runtime type. This is almost exactly the situation that static typing is designed to avoid in the first place though! It seems like somewhere we made a decision that was unsound without realizing it.

**Comment by turbolent** [comment]
- We should at least add a dedicated runtime check for accesses / flattening, checking element's dynamic type (`interpreter.StaticType`) against created reference type
- Later we could also improve static type checking. Options:
  - Forbid creation of references to type-erased type (e.g. `&[&R]` to `&[AnyStruct]` will create `&&R` on access)
  - Remove support for type-erasing references, i.e. make references NOT a subtype of `AnyStruct`
