### ISSUE TITLE
Handle recursive string conversion of values

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#349]
### Problem

The `String()` function of `interpreter.Value`s might be called on values which are recursive through a reference.

### Steps to Reproduce

https://forum.onflow.org/t/fatal-error-stack-overflow/569

### Acceptance Criteria

- [ ] No stack overflow

**Comment by turbolent** [comment]
@SupunS could you please have a look at this one? It falls in the reliability effort. 

I think this can be implemented similar to how e.g. dynamic type checks are now handling this

**Comment by SupunS** [comment]
A question would be what do we print if we find a direct/indirect self-reference?

Considering the below struct:
```
pub struct Foo {
    pub(set) var a: &Foo?
    pub var b: Int
    pub var c: String
}
```

A few suggestions:

- For all references, print something to say 'this' is a reference to 'that' value. e.g: `&Foo`, rather than printing the content of `Foo`. Somewhat similar to the reference type. But the downside is, if there are multiple reference values, `string()` wouldn't indicate which one is referring to which.
- Do the above only if we find a self-reference. Otherwise, print the value. Cons: output would be a bit inconsistent.
- Let the pattern recurse for `k` number of levels, and then print some notion (e.g: ellipsis '`...`') to say it is continuing.
  e.g: 
  Value string representation would be:
  ```
  Foo(
     a: Foo(
        a: Foo(
           a: ...
           b: 4
           c: "hello"
        )
        b: 4
        c: "hello"
     )
     b: 4
     c: "hello"
  )
  ```

**Comment by turbolent** [comment]
@SupunS I think something like option 1 should be sufficient for now, i.e., a reference is printed as just e.g. `&Foo`, "this is a reference to a value which has type `Foo`"

**Comment by turbolent** [comment]
Great thoughts and proposals 👍

**Comment by SupunS** [comment]
Seems we can't print the `&` followed by type name, because static type information is not available for containers (https://github.com/onflow/cadence/issues/870).
e.g:
```kotlin
var map: {String: AnyStruct} = {}
var map_ref = &map as &{String: AnyStruct}

// cyclic reference
map_ref["self"] = map_ref
```

**Comment by SupunS** [comment]
We could go with option-3, but I like the simplicity of option-1.

From a different perspective: I'm also OK with keeping the current behavior (infinite recursion), at least for now, because I wouldn't really call this problem a bug, but rather the expected behavior for trying to print a cyclic object tree (all the other programming languages have the same behavior).

**Comment by turbolent** [comment]
@SupunS I'll grab this one and will open a PR shortly
