### ISSUE TITLE
Operationalize Source compatibility suite

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3608]
## Goal

- Ensure that unit tests of ecosystem projects (e.g. [Flow core contracts](https://github.com/onflow/flow-core-contracts/)) pass for new Cadence releases
- Once done, we don't need #2503 
- Ask community for any repos they would like to be added to the compatibility check

## Scope

- Clone Git repo of repository of the ecosystem project
- Update the configuration to use latest Cadence version
- Run tests and ensure they pass

## Context

- Current code lives in https://github.com/onflow/cadence/tree/master/compat
- Current code rewrites Cadence code (e.g. updates import statements), and parses and typechecks it. 
  This is hard to maintain/brittle, we might want to remove this functionality
- Some projects, like the [Flow core contracts](https://github.com/onflow/flow-core-contracts/), have their tests are written in Go and use Cadence as a Go dependency
- Some projects use the [Cadence Testing framework](https://cadence-lang.org/docs/testing-framework)

**Comment by turbolent** [comment]
@RZhang05 Some notes:

The current implementation (https://github.com/onflow/cadence/blob/master/compat/main.py) clones a repo, rewrites the import statements so they can be resolved to files in the cloned repo, and parses and typechecks the code.

Rewriting the import statements is brittle, because the code in the tested repo might change, frequently.

So to begin with, maybe we can just keep the repo cloning, and remove/disable the functionality in the suite that rewrites the import statements, parses, and typechecks. 

Instead, as also @SupunS suggested, we can just run the test suite in the cloned repo, but with the latest/current Cadence version. For repos that have their tests written in Go (usually in a Go module in `lib/go/test`, e.g. https://github.com/onflow/flow-core-contracts/tree/master/lib/go/test), we can use `go.mod` `replace` statement to update the Cadence dependency. See https://go.dev/ref/mod#go-mod-file-replace. The `go mod edit` command can add/edit to `go.mod` file and add/edit the `replace` statement
