### ISSUE TITLE
Stored run-time types can't be used to specify a type of variable

### ISSUE THREAD

**Issue by MaxStalker** [onflow/cadence#413]
### Issue to be solved
If you try to identify the type of variable using previously stored Type value it will fail with inability to find type declaration in scope, even though it is properly created, stored and can be accessed.

### Instructions
Deploy following code to account 0x01
```
pub contract Base {
    pub let SpecialType: Type
    pub let description: String

    init(){
        self.description = "This contract provides a set of types to use"
        self.SpecialType = Type<{String: String}>()
    }
}
```
Now you should be able to execute this script, showing that both fields are stored on chain in proper shape and form
```
import Base from 0x01
pub fun main(){
    log(Base.description)     //  outputs: \"This contract provides a set of types to use\"
    log(Base.SpecialType)    // outputs: Type<{String: String}>

    let test = {"Hello": "World"}
    log(test.isInstance(Base.SpecialType))
}
```

But deployment of this contract will fail with error:
```
import Base from 0x01

pub contract TypeUser {
    pub let customProperty: Base.SpecialType  // ❌ cannot find type in this scope: `Base.SpecialType`. not found in this scope

    init(){
        log(Base.description)
        self.customProperty = {"Hello":"World"}
    }
}
``` 

But we can still use it inside of `isInstance` method:
```
import Base from 0x01

pub contract TypeUser {
    pub let customProperty: {String: String}

    init(){
        log(Base.description)
        self.customProperty = {"Hello":"World"}
    }

    pub fun isSpecial(item: AnyStruct): Bool {
        return item.isInstance(Base.SpecialType)
    }
}
``` 

Calling following script will work as expected
```
import Base from 0x1cf0e2f2f715450
import TypeUser from 0x179b6b1cb6755e31

pub fun main(){
    log(TypeUser.isSpecial(item: {"Hello":"World"}))
}

**Comment by turbolent** [comment]
It seems like there's some misunderstanding here.

`Base.SpecialType` has the type `Type`, so the *value* is a run-time type.

Basically, what's right of a `:` is the type annotation, which is on the type level, and what is right of a `=` is the value, which is on the value level. There are two separate "spaces", it's not possible to use value level values on the type level.

`let customProperty: Base.SpecialType` is (correctly) not valid, because there is no type-level type declaration named `SpecialType`. 

What you're trying to do, but is impossible, is to use the value of the field `SpecialType` on the type-level. This is not possible, because the static analysis, the type checker, would need to run the program to get the type value.

I'm happy to explain this further, it's a bit hard in written form.

I see though what you're trying to do. If you'd want to parameterize a type declaration, we would need generics. That allow the type checker to know about the type on the type-level, and then we could have support on the value level to get the run-time type for the type argument.

For example:

```swift
struct Wrapper<T> {
   let value: T

   init(value: T) {
       self.value = value
   }

   fun getRuntimeType(): Type {
       return Type<T>()
   }
} 
```

Maybe it's somewhat visible how, instead of keeping the type in a field (`Base.SpecialType` in your example), it's kept in a type parameter.

**Comment by MaxStalker** [comment]
Thank you for thorough explanation, Bastian! 🙇‍♂️
