### ISSUE TITLE
Find join of types, improve inference

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#61]
## Context

Implement a function to return the least common supertype.

This improves type checking for:
- Conditionals: instead of just returning the left type (type of true branch) and requiring the right type (else branch) to be the same
- Array literals
- Dictionary literals

See ["Types and Programming Languages, 16.3 Joins and Meets"](https://books.google.ca/books?id=ti6zoAC9Ph8C&lpg=PA219&pg=PA218#v=onepage&q&f=false)

In the following example `y` should be inferred to `String?`:

```
let x: String? = ""
let y = true ? nil : x 
```

## Definition of Done

- Sema: 
  - [ ] Add function to find join of two or more types
  - [ ] Use join function for conditionals
  - [ ] Use join function for array literals
  - [ ] Use join function for dictionary literals
- [ ] Tests
- [ ] Documentation

**Comment by bluesign** [comment]
Sorry if this is not related but something I observed and curious if this fixes that:

`
   var  myDictionary = {
           1: true,
           2: false   
       }

  myDictionary = myDictionary as! {Int:AnyStruct};
  `

Currently, this gives a strange error and warning:
 
Error:
`mismatched types. expected {Int:Bool}, got {Int:</span>AnyStruct}`

Warning:
`force cast ('as!') from to {Int:AnyStruct} always succeeds`

**Comment by SupunS** [comment]
These errors are actually for two places.

The first error `mismatched types. expected {Int:Bool}, got {Int:AnyStruct}` is for the assignment: 
`myDictionary = ...`, where rhs-expr is forced to have `{Int:AnyStruct}`. But the variable is `{Int:Bool}`. Assigning a broader-type to a narrower-type is not allowed.

The second warning is for the cast: `myDictionary as! {Int:AnyStruct};`. because the upcasting/boxing is always guaranteed to succeed. 
i.e: Casting is not required.

So both the error and the warning are valid in this case.

The supertype calculation wouldn't change this behavior either. Supertype inferring only happens at the expression level. It wouldn't consider multiple statements for type infering.  The least common supertype for  `{1: true, 2: false}` (therefore, also for `myDictionary`) would still be `{Int:Bool}`.

**Comment by bluesign** [comment]
Thanks @SupunS, actually it makes sense when separating into two.
