### ISSUE TITLE
Getting the `Address` from a `Capability`

### ISSUE THREAD

**Issue by derekchiang** [onflow/cadence#721]
Currently there's no way to get the `Address` from a `Capability`.

My use case was that I had a function which accepts a `Capability`, and I wanted to emit an event that records the address, like this:

```
pub registerCapability(c: Capability) {
    emit CapabilityRegistered(address: c.getAddress()) // this isn't possible
}
```

**Comment by ceelo777** [comment]
Hello! I'd be interested in tackling this issue - I'm not sure exactly how to go about doing so. Is there an example elsewhere in the code base that I can look at for reference?

**Comment by robmyers** [comment]
You may be able to borrow the capability referenced by the resource and use Resource.owner from that.

This would have slightly different semantics from Capability.owner, but probably covers some of the common potential use cases for it.

**Comment by turbolent** [comment]
@ceelo777 That's great to hear!

If you are interested, we can quickly sync next week, I could show where changes are needed and answer question.

Steps:
1. Declare the field in the type: Declare the member for `CapabilityType`: 

   https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/sema/type.go#L6530-L6555

   Instead of declaring a function, declare a field, like here:

   https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/sema/type.go#L2798-L2808


2. Add a checker test, like here:
   
   https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/tests/checker/capability_test.go#L74-L90

   Instead of expecting an error, assert that the type of the global value is an address, like here:

   https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/tests/checker/capability_test.go#L317-L322

3. Implement the field in the value: Declare the member for `CapabilityValue`:
   
   https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/interpreter/value.go#L7057-L7076

4. Add an interpreter test here:
 
   https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/tests/interpreter/capability_test.go#L29-L75

**Comment by ceelo777** [comment]
> @ceelo777 That's great to hear!
> 
> If you are interested, we can quickly sync next week, I could show where changes are needed and answer question.
> 
> Steps:
> 
>     1. Declare the field in the type: Declare the member for `CapabilityType`:
>        https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/sema/type.go#L6530-L6555
>        
>        Instead of declaring a function, declare a field, like here:
>        https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/sema/type.go#L2798-L2808
> 
>     2. Add a checker test, like here:
>        https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/tests/checker/capability_test.go#L74-L90
>        
>        Instead of expecting an error, assert that the type of the global value is an address, like here:
>        https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/tests/checker/capability_test.go#L317-L322
> 
>     3. Implement the field in the value: Declare the member for `CapabilityValue`:
>        https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/interpreter/value.go#L7057-L7076
> 
>     4. Add an interpreter test here:
>        https://github.com/onflow/cadence/blob/1e61ffa65cd977f1baab73a36dd639ac6bcd4bf2/runtime/tests/interpreter/capability_test.go#L29-L75

Thank you! I'll try going about it on my own, and if I can't get it I'll be sure to ask you questions
