### ISSUE TITLE
Allow interpreter instantiation in runtime

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#859]
### Issue To Be Solved

After the prerequisite (Contract Function Call)[https://github.com/onflow/cadence/issues/888] the next improvement is  to instantiate and re-use an interpreter for a specific location, e.g. for a service account contract, to avoid the overhead of a transaction (parsing, checking, argument validity checks, etc.)

### Suggested Solution

Add a function to `Runtime` that, given a context, returns an interpreter, 
e.g. `NewInterpreter(context Context) (*interpreter.Interpreter, error)`

### Context

Transaction fee deduction in FVM could be further (besides https://github.com/onflow/cadence/issues/888) optimized by instantiating an interpreter for the contract once, re-using it for all transactions, and calling the contract function directly.

The Issue that needs to be solve is, how does the fact that there is a separate hostEnv reference  for each transaction

**Comment by janezpodhostnik** [comment]
Looking at the cpu profile from canary testing:
![image](https://user-images.githubusercontent.com/67895329/119867917-b0bc8100-bf1e-11eb-95f1-9b2eaf9f7cf0.png)

The TransactionInvokator has three parts:
- run the transaction
- check storage
- deduct fees

All of these three parts could easily share a hostEnv and thus an Interpreter. This would cut down time needed for creating (and loading stuff into) an Interpreter. 

Usually any transaction you make needs to load the FungibleToken and  FlowToken directly or indirectly. This also needs to be re-done during check storage and deduct fees. Instead of loading these contracts (on average) 3 times we would load them once. Which would roughly mean that the sections that are highlighted in the screenshot would be cut down by two thirds.

**Comment by turbolent** [comment]
@janezpodhostnik Should we close this issue for now?

**Comment by turbolent** [comment]
Direct contract calls should now be efficient
