### ISSUE TITLE
Validate strings to be UTF-8

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#966]
### Issue To Be Solved

Strings in Cadence are assumed to be valid UTF-8. This is the case when string literals are parsed, but there are other means of constructing a string value which also need to be ensured to be valid.

### Suggest A Solution

- Validate input is UTF-8 in `cadence.NewString`, so that the preparation of a value client-side already fails there

### Context

https://axiomzen.slack.com/archives/CEXKUH74G/p1622587881117800

**Comment by turbolent** [comment]
@SupunS Could you please grab this?

**Comment by SupunS** [comment]
I think we don't have to escape non-utf8 characters at `interpreter.NewStringValue` level, because it would add an overhead for string values constructed using literals - which is the more prominent use-case. Instead, we could add a validation/escaping at the time of importing the value to the program.

Having said that, the json encoder also already does this escaping: https://github.com/golang/go/blob/dc8f87b7493e173d65d3587389cc41468ba16dc0/src/encoding/json/encode.go#L250:L253

So I think we don't have to do the same inside cadence. Could simply add a test case to validate this.

**Comment by SupunS** [comment]
I didn't quite understand the `decodeHex` use-case though. Maybe I'm missing something?

**Comment by turbolent** [comment]
Yeah, maybe `interpreter.NewString()` isn't the best place like you described, so instead we should do it in the public `cadence.NewString`: This function is the public interface and used by users through the Go SDK – validating there will already prevent users sending invalid values client-side (and then server-side the JSON decoder will already validate it too).

Yeah, mentioning `decodeHex` was wrong, I removed it 👍
